prj_Admission_DT/Projet_admission/admission/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_view, name='index'),
    path('programme/', programme_view, name='programme'),   
    path('contact/', contact_view, name='contact'),
    path('propos/', propos_view, name='propos'),
    path('admission/', include("Utilisateurs.urls")),
    path('informations/', include("informations.urls")),
    path('demande_admission/', include('demande_admission.urls')),

]

prj_Admission_DT/Projet_admission/demande_admission/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', base_demande_view, name='base_demande'),
    path('programme', etape_1_programme, name='etape_1'),
    path('information', etape_2_information, name='etape_2'),
    path('document', etape_3_document, name='etape_3'),
    path('payer', etape_4_payer, name='etape_4'),
    path('confrimer_payer', etape_5_confirmer, name='etape_5'),
     path('detail_confirmation', details_confirmation, name='details_confirmation')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prj_Admission_DT/Projet_admission/demande_admission/models.py
from django.db import models
from datetime import datetime
from django.conf import settings
from django.utils.html import format_html
import os
from django.urls import reverse
# -------------------------------Table Programme----------------------------------------------------
class Programme(models.Model):
    TITRE_CHOICES = (
        ('Génie logiciel', 'Génie logiciel'),
        ('Développement web', 'Développement web'),
        ('Analyse de données en biologie', 'Analyse de données en biologie'),
        ("Systèmes d'informatique en réseaux", "Systèmes d'informatique en réseaux"),
        ('Méthodes statistiques', 'Méthodes statistiques'),
        ('Mathématiques appliquées', 'Mathématiques appliquées'),
        ('Génie électrique', 'Génie électrique'),
        ('Design industriel', 'Design industriel'),
        ('Sciences politiques', 'Sciences politiques'),
        ('Études en intelligence artificielle', 'Études en intelligence artificielle'),
    )
    TYPE_CHOICES = (
        ('Baccalauréat','Baccalauréat'),
        ('Master','Master'),
        ('Doctorat','Doctorat'),
        ('Maîtrise','Maîtrise')
    )
    CYCLE_CHOICES = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
    )
    titre = models.CharField(max_length=100, choices=TITRE_CHOICES)
    type_admission = models.CharField(max_length=50, choices=TYPE_CHOICES)
    cycle = models.CharField(max_length=50, choices=CYCLE_CHOICES)
    trimestres = models.ManyToManyField('Trimestre', through='ProgrammeTrimestre', related_name='programmes')
    description = models.TextField()
    credits_programme = models.IntegerField()
    objectifs = models.TextField()
    duree_programme = models.IntegerField()
    prix_Programme = models.FloatField(max_length=8 ,default=36000.00)
    def __str__(self):
            return self.titre
    @classmethod
    def get_all_type_admission(cls):
        types_admission = cls.objects.values_list('type_admission', flat=True).distinct()
        return list(types_admission)
    @classmethod
    def get_programmes_by_type_admission(cls, type_admission):
        programmes = cls.objects.filter(type_admission=type_admission)
        return list(programmes)
# -------------------------------Table Information_Personnelle----------------------------------------------------
class Information_Personnelle(models.Model):
    nom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100)
    date_naissance = models.DateField() 
    lieu_naissance = models.CharField(blank=True,max_length=256)
    nationalite = models.CharField(max_length=30)
    adresse = models.TextField()
    telephone = models.CharField(max_length=20)
    email = models.EmailField(unique=True)
    sexe = models.CharField(max_length=8)
    status_Matrimoniale = models.CharField(max_length=50)
    role = models.CharField(max_length=50)
    def __str__(self):
        return self.nom + " "+ self.prenom + " "+ str(self.date_naissance)
# -------------------------------Table Trimestre----------------------------------------------------
class Trimestre(models.Model):
    TRIMESTRE_CHOICES = (
        ('Hiver', 'Hiver'),
        ('Été', 'Été'),
        ('Automne', 'Automne'),
    )
    nom = models.CharField(max_length=50, choices=TRIMESTRE_CHOICES)
    annee = models.IntegerField(default=2023) 
 

    def __str__(self):
        return f"{self.nom} {self.annee}"
    @classmethod
    def get_anne_trimest_by_anne(cls,annee):
        trimestre_anne=  cls.objects.filter(annee=annee)
        return trimestre_anne

# -------------------------------Table ProgrammeTrimestre----------------------------------------------------

class ProgrammeTrimestre(models.Model):
    programme = models.ForeignKey(Programme, on_delete=models.CASCADE)
    trimestre = models.ForeignKey(Trimestre, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.programme} {self.trimestre}"
    @classmethod
    def get_programme_trimestre(cls,programme):
        programme_trimestre = cls.objects.filter(programme=programme)
        for i in programme_trimestre:
            return i

# -------------------------------Table Doucument_Fournir----------------------------------------------------
from django.db import models

def chemin_telechargement(instance, filename):
    return f"documents/{instance.pk}/{filename}"

class Document_Fournir(models.Model):
    releve_note = models.FileField(upload_to=chemin_telechargement)
    attestation = models.FileField(upload_to=chemin_telechargement)
    lettre_motivation = models.FileField(upload_to=chemin_telechargement)
    piece_identite = models.FileField(upload_to=chemin_telechargement)
    acte_Naissance = models.FileField(upload_to=chemin_telechargement)

    def pdf_link(self, field_name):
        file_field = getattr(self, field_name)
        if file_field:
            return format_html(
                '<a href="{}" target="_blank">Ouvrir </a>',
                reverse('admin:view_document', args=[self.pk, field_name])
            )
        return 'No PDF available'

    pdf_link.allow_tags = True
    pdf_link.short_description = 'PDF Link'

    def __str__(self):
        return "Documents Fournis"
# -------------------------------Table Coordonne_Bancaire----------------------------------------------------

class Coordonne_Bancaire(models.Model):
    Identifiant = models.CharField("Nom sur la Carte ",max_length=100)
    num_Bancaire = models.CharField("Numéro de banque", max_length=250)
    code_banque = models.CharField("Code Banque",max_length=10)
    date_expiration =models.CharField(max_length=10)
    def __str__(self):
        return self.Identifiant

# -------------------------------Table Paiement----------------------------------------------------

import random
import string

def generate_payment_number():
    return ''.join(random.choices(string.ascii_uppercase + string.digits, k=10))
class Paiement(models.Model):
    methode_paiement = models.CharField(max_length=100)
    frais_admission = models.FloatField(max_length=6)
    Coordonne_Bancaire = models.ForeignKey(Coordonne_Bancaire, on_delete=models.CASCADE)
    datelimite=models.DateField()
    numero_paiement=models.CharField(max_length=25)


# -------------------------------Table Demander----------------------------------------------------
from Utilisateurs.models import Utilisateurs
class Demander_Admission(models.Model):
    CHOIX_STATUT = [
        ('accepte', 'Accepté'),
        ('refus', 'Refusé'),
        ('attente', 'En Attente'),
    ]
       
    demandeur = models.OneToOneField(Utilisateurs,on_delete=models.CASCADE)
    date_Soumision = models.DateField()
    ProgrammeTrimestre = models.ForeignKey(ProgrammeTrimestre,on_delete=models.CASCADE)
    Document_Fournir = models.ForeignKey(Document_Fournir,on_delete=models.CASCADE)
    Information_Personnel = models.ForeignKey(Information_Personnelle,on_delete=models.CASCADE)
    Paiement_Admission = models.ForeignKey(Paiement, on_delete=models.CASCADE)
    statut_demande = models.CharField(max_length=10,choices=CHOIX_STATUT,default='attente')
    

    # def __str__(self):
    #     return f"{self.Information_Personnel.nom  }"
        

prj_Admission_DT/Projet_admission/demande_admission/templates/demande_admission/base_demande.html
{% extends 'base.html' %} {% load static %} {% block extra_css %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/base_demande.css' %}"
/>
{% endblock %} {% block content %}
<div class="title">
  <h1>Type de demande : {{ type_admission }}</h1>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h3>Étapes</h3>
      <ul>
        {% if step_1_validated %}
        <li>
          <a href="{% url 'etape_1' %}">Étape 1 : Programmes demandés </a>
        </li>
        {% elif step_1_validated_icon %}
        <li>
          Étape 1 : Programmes demandés
          <img
            src="{% static 'img/valide.jpg' %}"
            alt="validated"
            class="icon"
            style="width: 20px; height: 20px; margin-left: auto"
          />
        </li>
        {% else %}
        <li>Étape 1 : Programmes demandés</li>
        {% endif %} {% if step_2_validated %}
        <li>
          <a href="{% url 'etape_2' %}"
            >Étape 2 : Informations d'identification</a
          >
        </li>
        {% elif step_2_validated_icon %}
        <li>
          Étape 2 : Informations d'identification
          <img
            src="{% static 'img/valide.jpg' %}"
            alt="validated"
            class="icon"
            style="width: 20px; height: 20px; margin-left: auto"
          />
        </li>
        {% else %}
        <li>Étape 2 : Informations d'identification</li>
        {% endif %} {% if step_3_validated %}
        <li class="validated">
          <a href="{% url 'etape_3' %}">Étape 3 : Documents à fournir</a>
        </li>
        {% elif step_3_validated_icon %}
        <li>
          Étape 3 : Documents à fournir
          <img
            src="{% static 'img/valide.jpg' %}"
            alt="validated"
            class="icon"
            style="width: 20px; height: 20px; margin-left: auto"
          />
        </li>
        {% else %}
        <li>Étape 3 : Documents à fournir</li>
        {% endif %} {% if step_4_validated %}
        <li class="validated">
          <a href="{% url 'etape_4' %}">Étape 4 : Paiement</a>
        </li>
        {% elif step_4_validated_icon %}
        <li>
          Étape 4 : Paiement
          <img
            src="{% static 'img/valide.jpg' %}"
            alt="validated"
            class="icon"
            style="width: 20px; height: 20px"
          />
        </li>
        {% else %}
        <li>Étape 4 : Paiement</li>
        {% endif %}{% if step_5_validated %}
        <li class="validated">
          <a href="{% url 'etape_5' %}">Étape 5 : Confirmation</a>
        </li>
        {% elif step_5_validated_icon %}
        <li>
          Étape 5 : Confirmation
          <img
            src="{% static 'img/valide.jpg' %}"
            alt="validated"
            class="icon"
            style="width: 20px; height: 20px"
          />
        </li>
        {% else %}
        <li>Étape 5 : Confirmation</li>
        {% endif %}
      </ul>
    </div>
    <div class="col-md-6">
      <div class="image_container">
        <img
          src="{% static 'img/image_demande.jpeg' %}"
          alt="Student Image"
          class="Student_Image"
        />
      </div>
    </div>
  </div>
</div>
{% endblock %}

prj_Admission_DT/Projet_admission/demande_admission/templates/demande_admission/details_confirmation.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <center><h1><Details></Details></h1></center>
</div>
{% endblock %}

prj_Admission_DT/Projet_admission/demande_admission/templates/demande_admission/etape_1_programme.html
{% extends 'base.html' %} {% load static %} {% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/etap_4.css' %}" />
<script type="text/javascript" src="{% static 'js/etap_4.js' %}"></script>
{% endblock %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <center><h1>Choisir un Programme et un Trimestre</h1></center>
      <form method="post">
        {% csrf_token %}
        <div class="Trimestre inline">
          <p>
            <strong>Choisir un Trimestre:</strong>
            {% for trimestre in Trimestre %}
            <label for="{{ trimestre.nom }}" style="font-size: 15px"
              >{{ trimestre.nom }} - {{ trimestre.annee }}</label
            >
            <input
              type="radio"
              name="Trimestre"
              value="{{ trimestre.nom }} {{ trimestre.annee }}"
              required
            />
            {% endfor %}
          </p>
        </div>
        <div class="program-list inline">
          <h3>Choisir un Programme:</h3>
          <select name="programme" id="programme">
            {% for program in programme %}
            <option value="{{ program.titre }}">{{ program.titre }}</option>
            {% endfor %}
          </select>
        </div>
        <button type="submit" class="btn btn-primary">Suivant</button>
      </form>
      <p style="color: red">{{ Erreur }}</p>
    </div>
    <div class="col-md-6">
      <div id="search-container">
        <input
          type="text"
          name="search_program"
          placeholder="Rechercher un programme..."
        />
        <button type="submit">Rechercher</button>
      </div>
      <p>
        Consultez nos programmes pour trouver celui qui vous convient le mieux.
      </p>
    </div>
  </div>
</div>
{% endblock %}

prj_Admission_DT/Projet_admission/demande_admission/templates/demande_admission/etape_2_information.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="registration-form">
        <form method="post" action="">
          {% csrf_token %}
          <h2>Informations Personnelles</h2>
          <div class="form-group">
            <label for="id_nom">Nom:</label>
            <input type="text" name="nom" id="id_nom" required />
          </div>
          <div class="form-group">
            <label for="id_prenom">Prénom:</label>
            <input type="text" name="prenom" id="id_prenom" required />
          </div>
          <div class="form-group">
            <label for="id_date_naissance">Date de Naissance:</label>
            <input
              type="date"
              name="date_naissance"
              id="id_date_naissance"
              required
            />
          </div>
          <div class="form-group">
            <label for="id_lieu_naissance">Lieu de Naissance:</label>
            <input type="text" name="lieu_naissance" id="id_lieu_naissance" />
          </div>
          <div class="form-group">
            <label for="nationalite">Nationalité:</label>
            <input type="text" name="nationalite" id="nationalite" />
          </div>
          <div class="form-group">
            <label for="adresse">Adresse:</label>
            <input type="text" name="adresse" id="adresse" />
          </div>
          <div class="form-group">
            <label for="telephone">Téléphone:</label>
            <input type="text" name="telephone" id="telephone" />
          </div>
          <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" name="email" id="email" />
          </div>
          <div class="form-group">
            <label for="status_Matrimoniale">Statut Matrimonial:</label>
            <input
              type="text"
              name="status_Matrimoniale"
              id="status_Matrimoniale"
            />
          </div>
          <div class="form-group">
            <label for="sexe">Sexe:</label>
            <select name="sexe" id="sexe">
              <option value="homme">Homme</option>
              <option value="femme">Femme</option>
            </select>
          </div>
          <div class="form-group">
            <label for="role">Rôle:</label>
            <input type="text" name="role" id="role" />
          </div>

          <button type="submit" class="btn btn-primary">Suivant >>></button>
        </form>
        <p style="color: red; text-align: center; margin-top: 30px">
          {{ erreur }}
        </p>
      </div>
    </div>
    <div class="col-md-6">
      <div class="image_container">
        <img
          src="{% static 'img/registre.jpg' %}"
          alt="Student Image"
          class="icone"
        />
      </div>
    </div>
  </div>
</div>
{% endblock %} {% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/etape_2.css' %}" />
{% endblock %}

prj_Admission_DT/Projet_admission/demande_admission/templates/demande_admission/etape_3_document.html
{% extends 'base.html' %} {% block content %}
<style>
  .type_admission {
    text-align: center;
    color: cornflowerblue;
    font-size: 18px;
    margin-top: 20px;
    font-family: Cambria, Cochin, Georgia, Times, "Times New Roman", serif;
    width: 450px;
    height: 50px;
    overflow: hidden;
    margin-right: 0px;
    margin-left: 70px;
    /*border: 1px solid #000; Ajouter une bordure pour mieux visualiser la zone de défilement */
  }
</style>
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="card mt-5">
        <div class="card-body">
          <h2 class="card-title text-center">Soumettre les Documents</h2>
          <form
            method="post"
            enctype="multipart/form-data"
            action=""
            class="needs-validation"
            novalidate
          >
            {% csrf_token %} {% if type_admission == 'Baccalauréat' %}
            <marquee
              direction="left"
              behavior="alternate"
              class="type_admission"
              >Diplôme prérequis pour le {{ type_admission }} :<strong
                >Diplôme d'études secondaires</strong
              >
              <p>Toutes les documents sont en Format pdf</p>
            </marquee>
            <div class="mb-3">
              <label for="releve_note"> 📄 Relevé de notes </label>
              <input
                type="file"
                class="form-control"
                name="releve_note"
                id="releve_note"
                required
              />
              <div class="invalid-feedback">Veuillez choisir un fichier.</div>
            </div>
            <div class="mb-3">
              <label for="attestation"> 📜 Attestation </label>
              <input
                type="file"
                class="form-control"
                name="attestation"
                id="attestation"
                required
              />
              <div class="invalid-feedback">Veuillez choisir un fichier.</div>
            </div>

            <div class="mb-3">
              <label for="lettre_motivation"> ✉️ Lettre de motivation </label>
              <input
                type="file"
                class="form-control"
                name="lettre_motivation"
                id="lettre_motivation"
                required
              />
              <div class="invalid-feedback">Veuillez choisir un fichier.</div>
            </div>

            <div class="mb-3">
              <label for="piece_identite"> 🆔 Pièce d'identité </label>
              <input
                type="file"
                class="form-control"
                name="piece_identite"
                id="piece_identite"
                required
              />
              <div class="invalid-feedback">Veuillez choisir un fichier.</div>
            </div>

            <div class="mb-3">
              <label for="acte_naissance"> 👶 Acte de Naissance </label>
              <input
                type="file"
                class="form-control"
                name="acte_Naissance"
                id="acte_naissance"
                required
              />
              <div class="invalid-feedback">Veuillez choisir un fichier.</div>
            </div>
            {% endif %} {% if type_admission == 'Master' %}
            <marquee
              direction="left"
              behavior="alternate"
              class="type_admission"
              >Diplôme prérequis pour le {{ type_admission }} :
              <strong>Baccalauréat</strong>
              <p>Toutes les documents sont en Format pdf</p></marquee
            >
            <div class="mb-3">
              <label for="releve_note"> 📄 Relevé de notes </label>
              <input
                type="file"
                class="form-control"
                name="releve_note"
                id="releve_note"
                required
              />
              <div class="invalid-feedback">Veuillez choisir un fichier.</div>
            </div>
            <div class="mb-3">
              <label for="attestation"> 📜 Attestation </label>
              <input
                type="file"
                class="form-control"
                name="attestation"
                id="attestation"
                required
              />
              <div class="invalid-feedback">Veuillez choisir un fichier.</div>
            </div>

            <div class="mb-3">
              <label for="lettre_motivation"> ✉️ Lettre de motivation </label>
              <input
                type="file"
                class="form-control"
                name="lettre_motivation"
                id="lettre_motivation"
                required
              />
              <div class="invalid-feedback">Veuillez choisir un fichier.</div>
            </div>

            <div class="mb-3">
              <label for="piece_identite"> 🆔 Pièce d'identité </label>
              <input
                type="file"
                class="form-control"
                name="piece_identite"
                id="piece_identite"
                required
              />
              <div class="invalid-feedback">Veuillez choisir un fichier.</div>
            </div>

            <div class="mb-3">
              <label for="acte_naissance"> 👶 Acte de Naissance </label>
              <input
                type="file"
                class="form-control"
                name="acte_Naissance"
                id="acte_naissance"
                required
              />
              <div class="invalid-feedback">Veuillez choisir un fichier.</div>
            </div>
            {% endif %} {% if type_admission == 'Doctorat' %}
            <marquee
              direction="left"
              behavior="alternate"
              class="type_admission"
              >Diplôme prérequis pour le {{ type_admission }} :
              <strong>Master</strong>
              <p>Toutes les documents sont en Format pdf</p></marquee
            >
            <div class="mb-3">
              <label for="releve_note"> 📄 Relevé de notes </label>
              <input
                type="file"
                class="form-control"
                name="releve_note"
                id="releve_note"
                required
              />
              <div class="invalid-feedback">Veuillez choisir un fichier.</div>
            </div>
            <div class="mb-3">
              <label for="attestation"> 📜 Attestation </label>
              <input
                type="file"
                class="form-control"
                name="attestation"
                id="attestation"
                required
              />
              <div class="invalid-feedback">Veuillez choisir un fichier.</div>
            </div>

            <div class="mb-3">
              <label for="lettre_motivation"> ✉️ Lettre de motivation </label>
              <input
                type="file"
                class="form-control"
                name="lettre_motivation"
                id="lettre_motivation"
                required
              />
              <div class="invalid-feedback">Veuillez choisir un fichier.</div>
            </div>

            <div class="mb-3">
              <label for="piece_identite"> 🆔 Pièce d'identité </label>
              <input
                type="file"
                class="form-control"
                name="piece_identite"
                id="piece_identite"
                required
              />
              <div class="invalid-feedback">Veuillez choisir un fichier.</div>
            </div>

            <div class="mb-3">
              <label for="acte_naissance"> 👶 Acte de Naissance </label>
              <input
                type="file"
                class="form-control"
                name="acte_Naissance"
                id="acte_naissance"
                required
              />
              <div class="invalid-feedback">Veuillez choisir un fichier.</div>
            </div>
            {% endif %} {% if type_admission == 'Maîtrise' %}
            <marquee
              direction="left"
              behavior="alternate"
              class="type_admission"
              >>Diplôme prérequis pour la {{ type_admission }} :
              <strong>Baccalauréat</strong>
            </marquee>
            <div class="mb-3">
              <label for="releve_note"> 📄 Relevé de notes </label>
              <input
                type="file"
                class="form-control"
                name="releve_note"
                id="releve_note"
                required
              />
              <div class="invalid-feedback">Veuillez choisir un fichier.</div>
            </div>
            <div class="mb-3">
              <label for="attestation"> 📜 Attestation </label>
              <input
                type="file"
                class="form-control"
                name="attestation"
                id="attestation"
                required
              />
              <div class="invalid-feedback">Veuillez choisir un fichier.</div>
            </div>

            <div class="mb-3">
              <label for="lettre_motivation"> ✉️ Lettre de motivation </label>
              <input
                type="file"
                class="form-control"
                name="lettre_motivation"
                id="lettre_motivation"
                required
              />
              <div class="invalid-feedback">Veuillez choisir un fichier.</div>
            </div>

            <div class="mb-3">
              <label for="piece_identite"> 🆔 Pièce d'identité </label>
              <input
                type="file"
                class="form-control"
                name="piece_identite"
                id="piece_identite"
                required
              />
              <div class="invalid-feedback">Veuillez choisir un fichier.</div>
            </div>

            <div class="mb-3">
              <label for="acte_naissance"> 👶 Acte de Naissance </label>
              <input
                type="file"
                class="form-control"
                name="acte_Naissance"
                id="acte_naissance"
                required
              />
              <div class="invalid-feedback">Veuillez choisir un fichier.</div>
            </div>
            {% endif %}
            <button type="submit" class="btn btn-success btn-block mt-4">
              📤 Soumettre
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

prj_Admission_DT/Projet_admission/demande_admission/templates/demande_admission/etape_5_confirmer.html
{% extends 'base.html' %} {% load static %} {% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/etape_5.css' %}" />
<style>
  strong {
    font-family: "NouvellePolice", sans-serif;
    font-weight: bold;
  }
</style>
{% endblock %} {% block content %}
<div class="container">
  <img
    src="{% static 'img/icone_uqam.jpeg' %}"
    alt="UQAM Logo"
    class="uqam_logo"
    style="width: 50px; height: 20px"
  />
  <center>
    <h1>Veuillez confirmer votre demande d'admission à l'UQAM</h1>
  </center>
  <p>Bonjour, {{ information_personnelle.nom }}</p>
  <p>
    Nee le <strong>{{ information_personnelle.date_naissance }}</strong> a {{ information_personnelle.lieu_naissance }}
  </p>
  <p>
    Nous sommes ravis de vous informer que votre demande d'admission à
    l'Université du Québec à Montréal (UQAM) vous pouvez bien confirmée.
  </p>
  <p>
    Programme sélectionné :
    <strong>{{ programme_trimestre.programme.titre }}</strong>
  </p>
  <p>
    Trimestre sélectionné :
    <strong
      >{{ programme_trimestre.trimestre.nom }} {{ programme_trimestre.trimestre.annee }}</strong
    >
  </p>
  <p>Type d'admission : <strong>{{ type_admissin }}</strong></p>

  <p>
    Vous pouvez maintenant confirmé votre demande d'admission. Veuillez prendre
    note que cette lettre de confirmation ne constitue pas une acceptation
    officielle. Vous recevrez une notification officielle dès que votre demande
    aura été examinée.
  </p>
  <div class="text-center mt-4">
    <form action="{% url 'etape_5' %}" method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-success">
        Confirmer la demande
      </button>
      <p style="color: red; margin-top: 20px">{{ error }}</p>
    </form>
  </div>
  <p>
    Merci de choisir l'UQAM pour poursuivre vos études supérieures. Nous sommes
    impatients de vous accueillir sur notre campus.
  </p>
  <p>
    Pour voir les détails de votre demande,
    <a href="{% url 'details_confirmation' %}">cliquez ici</a>.
  </p>
  <p>Cordialement,</p>
  <p>L'Équipe d'Admission<br />Université du Québec à Montréal</p>
  <img
    src="{% static 'img/icone_uqam.jpeg' %}"
    alt="UQAM Logo"
    class="uqam_logo"
    style="width: 50px; height: 20px; margin-left: 700px"
  />
</div>
{% endblock %}