prj_Admission_DT/Projet_admission/Utilisateurs/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', login_view, name='admission'),
    path('register/', register_user, name="register_user"),
    path('confirmer/',Confirmer_Couriel_view,name='confirmerCourriel'),
    path('accuiel/', pages_accuiel_view, name='accuiel'),
    path('profil/', profil_view, name='profil'),
    path('deconnexion/',deconnexion_view,name='deconnexion'),
    path('modification_profil/',modification_profil_view,name='modification_profil'),
    path('etat_demande/',etat_demande,name='etat_demande'),


]
# urlpatterns = [
#     path('', login_view, name='admission'),
#     path('register/', register_user, name="register_user"),
#     path('accuiel/', pages_accuiel_view, name='accuiel'),
#     path('profil/', profil_view, name='profil'),
#     path('deconnexion/',deconnexion_view,name='deconnexion'),
#     path('modification_profil/',modification_profil_view,name='modification_profil'),

# ]

prj_Admission_DT/Projet_admission/admission/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_view, name='index'),
    path('programme/', programme_view, name='programme'),   
    path('contact/', contact_view, name='contact'),
    path('propos/', propos_view, name='propos'),
    path('admission/', include("Utilisateurs.urls")),
    path('informations/', include("informations.urls")),
    path('demande_admission/', include('demande_admission.urls')),

]

prj_Admission_DT/Projet_admission/demande_admission/models.py
from django.db import models
from datetime import datetime
from django.conf import settings
from django.utils.html import format_html
import os
from django.urls import reverse
# -------------------------------Table Programme----------------------------------------------------
class Programme(models.Model):
    TITRE_CHOICES = (
        ('Génie logiciel', 'Génie logiciel'),
        ('Développement web', 'Développement web'),
        ('Analyse de données en biologie', 'Analyse de données en biologie'),
        ("Systèmes d'informatique en réseaux", "Systèmes d'informatique en réseaux"),
        ('Méthodes statistiques', 'Méthodes statistiques'),
        ('Mathématiques appliquées', 'Mathématiques appliquées'),
        ('Génie électrique', 'Génie électrique'),
        ('Design industriel', 'Design industriel'),
        ('Sciences politiques', 'Sciences politiques'),
        ('Études en intelligence artificielle', 'Études en intelligence artificielle'),
    )
    TYPE_CHOICES = (
        ('Baccalauréat','Baccalauréat'),
        ('Master','Master'),
        ('Doctorat','Doctorat'),
        ('Maîtrise','Maîtrise')
    )
    CYCLE_CHOICES = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
    )
    titre = models.CharField(max_length=100, choices=TITRE_CHOICES)
    type_admission = models.CharField(max_length=50, choices=TYPE_CHOICES)
    cycle = models.CharField(max_length=50, choices=CYCLE_CHOICES)
    trimestres = models.ManyToManyField('Trimestre', through='ProgrammeTrimestre', related_name='programmes')
    description = models.TextField()
    credits_programme = models.IntegerField()
    objectifs = models.TextField()
    duree_programme = models.IntegerField()
    prix_Programme = models.FloatField(max_length=8 ,default=36000.00)
    def __str__(self):
            return self.titre
    @classmethod
    def get_all_type_admission(cls):
        types_admission = cls.objects.values_list('type_admission', flat=True).distinct()
        return list(types_admission)
    @classmethod
    def get_programmes_by_type_admission(cls, type_admission):
        programmes = cls.objects.filter(type_admission=type_admission)
        return list(programmes)
# -------------------------------Table Information_Personnelle----------------------------------------------------
class Information_Personnelle(models.Model):
    nom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100)
    date_naissance = models.DateField() 
    lieu_naissance = models.CharField(blank=True,max_length=256)
    nationalite = models.CharField(max_length=30)
    adresse = models.TextField()
    telephone = models.CharField(max_length=20)
    email = models.EmailField(unique=True)
    sexe = models.CharField(max_length=8)
    status_Matrimoniale = models.CharField(max_length=50)
    role = models.CharField(max_length=50)
    def __str__(self):
        return self.nom + " "+ self.prenom + " "+ str(self.date_naissance)
# -------------------------------Table Trimestre----------------------------------------------------
class Trimestre(models.Model):
    TRIMESTRE_CHOICES = (
        ('Hiver', 'Hiver'),
        ('Été', 'Été'),
        ('Automne', 'Automne'),
    )
    nom = models.CharField(max_length=50, choices=TRIMESTRE_CHOICES)
    annee = models.IntegerField(default=2023) 
 

    def __str__(self):
        return f"{self.nom} {self.annee}"
    @classmethod
    def get_anne_trimest_by_anne(cls,annee):
        trimestre_anne=  cls.objects.filter(annee=annee)
        return trimestre_anne

# -------------------------------Table ProgrammeTrimestre----------------------------------------------------

class ProgrammeTrimestre(models.Model):
    programme = models.ForeignKey(Programme, on_delete=models.CASCADE)
    trimestre = models.ForeignKey(Trimestre, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.programme} {self.trimestre}"
    @classmethod
    def get_programme_trimestre(cls,programme):
        programme_trimestre = cls.objects.filter(programme=programme)
        for i in programme_trimestre:
            return i

# -------------------------------Table Doucument_Fournir----------------------------------------------------
from django.db import models

def chemin_telechargement(instance, filename):
    return f"documents/{instance.pk}/{filename}"

class Document_Fournir(models.Model):
    releve_note = models.FileField(upload_to=chemin_telechargement)
    attestation = models.FileField(upload_to=chemin_telechargement)
    lettre_motivation = models.FileField(upload_to=chemin_telechargement)
    piece_identite = models.FileField(upload_to=chemin_telechargement)
    acte_Naissance = models.FileField(upload_to=chemin_telechargement)

    def pdf_link(self, field_name):
        file_field = getattr(self, field_name)
        if file_field:
            return format_html(
                '<a href="{}" target="_blank">Ouvrir </a>',
                reverse('admin:view_document', args=[self.pk, field_name])
            )
        return 'No PDF available'

    pdf_link.allow_tags = True
    pdf_link.short_description = 'PDF Link'

    def __str__(self):
        return "Documents Fournis"
# -------------------------------Table Coordonne_Bancaire----------------------------------------------------

class Coordonne_Bancaire(models.Model):
    Identifiant = models.CharField("Nom sur la Carte ",max_length=100)
    num_Bancaire = models.CharField("Numéro de banque", max_length=250)
    code_banque = models.CharField("Code Banque",max_length=10)
    date_expiration =models.CharField(max_length=10)
    def __str__(self):
        return self.Identifiant

# -------------------------------Table Paiement----------------------------------------------------

import random
import string

def generate_payment_number():
    return ''.join(random.choices(string.ascii_uppercase + string.digits, k=10))
class Paiement(models.Model):
    methode_paiement = models.CharField(max_length=100)
    frais_admission = models.FloatField(max_length=6)
    Coordonne_Bancaire = models.ForeignKey(Coordonne_Bancaire, on_delete=models.CASCADE)
    datelimite=models.DateField()
    numero_paiement=models.CharField(max_length=25)


# -------------------------------Table Demander----------------------------------------------------
from Utilisateurs.models import Utilisateurs
class Demander_Admission(models.Model):
    CHOIX_STATUT = [
        ('accepte', 'Accepté'),
        ('refus', 'Refusé'),
        ('attente', 'En Attente'),
    ]
       
    demandeur = models.OneToOneField(Utilisateurs,on_delete=models.CASCADE)
    date_Soumision = models.DateField()
    ProgrammeTrimestre = models.ForeignKey(ProgrammeTrimestre,on_delete=models.CASCADE)
    Document_Fournir = models.ForeignKey(Document_Fournir,on_delete=models.CASCADE)
    Information_Personnel = models.ForeignKey(Information_Personnelle,on_delete=models.CASCADE)
    Paiement_Admission = models.ForeignKey(Paiement, on_delete=models.CASCADE)
    statut_demande = models.CharField(max_length=10,choices=CHOIX_STATUT,default='attente')
    

    # def __str__(self):
    #     return f"{self.Information_Personnel.nom  }"
        

prj_Admission_DT/Projet_admission/Utilisateurs/views.py
from django.conf import settings
from email.message import EmailMessage
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from django.shortcuts import render, redirect
# from .Class import Comptes
from .models import Utilisateurs
import random
from demande_admission.models import Programme
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import random

def send_confirmation_email(email, Nom_user):
    smtp_server = 'smtp.gmail.com'
    smtp_port = 587
    sender_email = 'anonymousteccart@gmail.com'
    sender_password = 'ddnh pgpe yape wchg'
    code_6 = ''.join(str(random.randint(0, 9)) for _ in range(6))

    message = MIMEMultipart("alternative")
    message["Subject"] = 'Confirmation: ouverture d\'un compte d\'Admission en ligne à l\'UQAM'
    message["From"] = sender_email
    message["To"] = email

    html = f"""\
    <html>
      <head></head>
      <body>
        <div style="font-family: Arial, sans-serif; background-color: #f6f6f6; padding: 20px;">
          <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; padding: 20px; border-radius: 5px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);">
            <h2 style="color: #007bff;">Confirmation: ouverture d'un compte d'Admission en ligne à l'UQAM</h2>
            <p>Bonjour, {Nom_user},</p>
            <p>Nous vous confirmons la création de votre compte d'admission en ligne de l'UQAM. Vous pouvez utiliser le code suivant pour finaliser votre inscription : <strong>{code_6}</strong>.</p>
            <p>Ce compte vous permettra de soumettre et de visualiser vos demandes d'admission à notre institution et de prendre connaissance des décisions prononcées.</p>
            <p>Nous vous remercions de votre intérêt envers l'UQAM et vous prions d'agréer nos salutations les plus cordiales.</p>
            <p>L'équipe de l'Admission.</p>
            <p>Note : Ne répondez pas à ce courriel. Celui-ci est généré automatiquement. Pour toute question, visitez le site : <a href="#" style="color: #007bff;">UQAM</a></p>
          </div>
        </div>
      </body>
    </html>
    """

    part = MIMEText(html, "html")
    message.attach(part)

    with smtplib.SMTP(smtp_server, smtp_port) as server:
        server.starttls()
        server.login(sender_email, sender_password)
        server.sendmail(sender_email, email, message.as_string())
    return code_6




def login_view(request):
    response = ''
    if request.method == 'POST':
        code_user = request.POST.get('code_user')
        password = request.POST.get('password')
        user, success = Utilisateurs.login_user(code_user=code_user, password=password)
        if success:
            request.session['user_id'] = user.get('id')
           # response.set_cookie('code_user', code_user)
            response= redirect('accuiel')
            return response
        else:
           context =  {"error_message" : 'Code utilisateur ou mot de passe incorrect. Veuillez réessayer.'}
           return render(request, 'Utilisateurs/login.html', context=context)
    return render(request, 'Utilisateurs/login.html')

def register_user(request):
    if request.method == "POST":
        code_user = request.POST.get('code_user')
        password = request.POST.get('password')
        email = request.POST.get('email')
        existing_code_user = Utilisateurs.objects.filter(code_user=code_user).first()
        if existing_code_user:
           context =  {"error_message" : 'Code utilisateur exist.Veuillez réessayer.'}
           return render(request, 'Utilisateurs/registre.html', context=context)
        request.session['code_user'] = code_user
        request.session['password'] = password
        request.session['email'] = email
        code = send_confirmation_email(email, code_user)
        request.session['code_6'] = code
        return redirect("confirmerCourriel")
    return render(request, 'Utilisateurs/registre.html')
def Confirmer_Couriel_view(request):
     if request.method == "POST":
            code_user = request.POST.get('code_confirmation')
            code = request.session.get('code_6')
            code_user_saved = request.session.get('code_user')
            password = request.session.get('password')
            email = request.session.get('email')
            
            if code_user == code:
                new_user = Utilisateurs.objects.create(code_user=code_user_saved, password=password, email=email, actifs=True)
                new_user.save()
                del request.session['code_6']
                del request.session['password']
                del request.session['email']
                return redirect("admission")
            else:
                error_message= 'Code utilisateur invalide. Veuillez réessayer.'
                return render(request, 'Utilisateurs/confirme_Courriel.html', {'error_message': error_message})
     return render(request, 'Utilisateurs/confirme_Courriel.html')
from demande_admission.models import Demander_Admission
def pages_accuiel_view(request):
    id_user = request.session['user_id']
    info_user,success = Utilisateurs.get_user_id(id_user)
    if success:
        user,success = Utilisateurs.get_user_id(id_user)
        user = user.get("code_user")
        user_instance = Utilisateurs.objects.get(code_user=user)
        demande_admission = Demander_Admission.objects.filter(demandeur=user_instance).first()
        #print(demande_admission)
        types_admission = Programme.get_all_type_admission()
        context = {
            'info_user' : info_user,
            'types_admission' : types_admission,
            'demande_admission' : demande_admission
        }
        if request.method == 'POST':
            type_admission = request.POST.get('type')
            request.session['type_admission'] = type_admission
            return redirect("base_demande")
        return render(request,'Utilisateurs/accueil.html',context=context)
    return render(request, 'Utilisateurs/accueil.html')


def profil_view(request):
    id_user = request.session['user_id']
    info_user,success = Utilisateurs.get_user_id(id_user)
    if success:
        context = {
            'info_user' : info_user,
        }
        return render(request,'Utilisateurs/accueil.html',context=context)
    return render(request, 'Utilisateurs/profil.html')
def deconnexion_view(request):
    del request.session['user_id']
    return redirect('admission')

def modification_profil_view(request):
    return render(request, 'Utilisateurs/modification_profil.html');
def etat_demande(request):
    id_user = request.session['user_id']
    user,success = Utilisateurs.get_user_id(id_user)
    user = user.get("code_user")
    user_instance = Utilisateurs.objects.get(code_user=user)
    demande_admission = Demander_Admission.objects.filter(demandeur=user_instance).first()
    context = {
        'demande_admission' : demande_admission
    }
    documents = demande_admission.Document_Fournir
   # releve_note = documents.releve_note
    atesttation = documents.attestation
    acte_naissance = documents.acte_Naissance
    lettre_motivation = documents.lettre_motivation
    piece_identite = documents.piece_identite
    # print(f"voila releve : {releve_note}")
    # print(f"voila attesation : {atesttation}")
    # print(f"voila acte naissance : {acte_naissance}")
    # print(f"voila lettre motivation : {lettre_motivation}")
    # print(f"voila pience identite : {piece_identite}")
    import cv2
    import pytesseract
    from PIL import Image
    from PyPDF2 import PdfFileWriter, PdfFileReader
    pytesseract.pytesseract.tesseract_cmd = r'C:\Users\KASSAMBARA ABRAMANE\source\repos\prj_Admission_DT\Tesseract-OCR\tesseract.exe'

    def extract_text_from_image(image_path):
        image = cv2.imread(str(image_path))
        if image is None:
          return print(f"Voila de l'image échouée : {image_path}")
        else:
         gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
         resized_image = cv2.resize(gray_image, None, fx=2, fy=2, interpolation=cv2.INTER_CUBIC)
         text = pytesseract.image_to_string(resized_image)
         text = pytesseract.image_to_string(gray_image)
         if text.strip() == "":
            print(f"Tesseract n'a pas pu extraire de texte de l'image : {image_path}")
         else:
            print(f"Texte extrait : {text}")
        return text
    #print(f'Chemin de l\'image : {releve_note}')
    text_releve_note = extract_text_from_image(lettre_motivation)
    print(f'Text Releve Note : {text_releve_note}')
    return render(request,'Utilisateurs/etat_demande.html',context=context)

prj_Admission_DT/Projet_admission/Utilisateurs/templates/Utilisateurs/accueil.html
{% extends 'base.html' %} {% load static %} {% block page_title %}Accueil
Étudiant{% endblock %} {% block extra_css %}
<link rel="stylesheet" href="{% static 'css/accuiel.css' %}" />
{% endblock %} {% block content %}
<div class="container">
  <div class="student_info">
    <h1>Demande d'admission à l'université</h1>
    <ul class="navbar">
      <li><a href="{% url 'deconnexion' %}">Déconnexion</a></li>
      <li><a href="{% url 'profil' %}">Profil</a></li>
      {% if demande_admission %}
      <li>
        <a href="{% url 'etat_demande' %}">Voir Etat de la demande </a>
      </li>
      {% endif %}
    </ul>
    <ul>
      <li>
        <img
          src="{% static 'img/user.png' %}"
          alt="Avatar de l'utilisateur"
          class="avatar"
          style="width: 20px; height: 20px"
        />
        Code Utilisateur : {{ info_user.code_user }}
      </li>
      <li>
        <img
          src="../../../static/img/email.png"
          alt="Icône d'e-mail"
          class="icon"
          style="width: 20px; height: 20px"
        />
        Email: {{ info_user.email }}
      </li>
      <!-- Ajoutez d'autres informations personnelles ici -->
    </ul>
    <p>
      Ici, vous trouverez toutes les informations importantes concernant votre
      parcours universitaire.
    </p>
    <h4>Faire une nouvelle demande d'admission</h4>

    <ul>
<ul class="button_list">
  <p>Types de demande :</p>
  {% for type in types_admission %}
    <li>
      <form method="post">
        {% csrf_token %}
        <input type="submit" name="type" value="{{ type }}" style="color: blue;">
      </form>
    </li>
  {% endfor %}
</ul>
  </div>
  {% endblock %} {% block extra_js %}
  <script type="text/javascript" src="{% static 'js/accueil.js' %}"></script>
  {% endblock %}
  <!-- !-- {% url 'demande_admission' %} -->
</div>

prj_Admission_DT/Projet_admission/Utilisateurs/templates/Utilisateurs/confirme_Courriel.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="registration-form">
        <form method="post" onsubmit="return test()">
          {% csrf_token %}
          <h2>Confirmation d'email</h2>
          <p>
            Veuillez saisir le code à 6 chiffres que vous avez reçu par email
            pour confirmer votre adresse email.
          </p>
          <div class="form-group">
            <label for="code_confirmation">Code de confirmation</label>
            <input
              type="text"
              id="code_confirmation"
              name="code_confirmation"
              maxlength="6"
              required
            />
          </div>
          <button type="submit" class="btn btn-primary">Confirmer</button>
        </form>
        <p
          id="Error"
          class="Error"
          style="
            color: red;
            margin-top: 20px;
            font-family: 'Times New Roman', Times, serif;
          "
        >
          {{ error_message }}
        </p>
        <!-- <p class="register_link">
          Vous n'avez pas de compte ?
          <a href="{% url 'admission' %}">S'inscrire</a>
        </p>
      </div> -->
      </div>
    </div>
    <div class="col-md-6">
      <div class="image-container">
        <img
          src="{% static 'img/registre.jpg' %}"
          alt="Image d'étudiant"
          class="student_image"
        />
      </div>
    </div>
  </div>
  {% endblock %} {% block extra_css %}
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'css/confirmeCourreil.css' %}"
  />
  {% endblock %} {% block extra_js %}
  <script type="text/javascript" src="{% static 'js/registre.js' %}"></script>
  {% endblock %}
</div>

prj_Admission_DT/Projet_admission/Utilisateurs/templates/Utilisateurs/etat_demande.html
{% extends 'base.html' %} {% load static %} {% block page_title %}État de la
Demande{% endblock %} {% block content %}
<div class="demande-container">
  <h2>État de la Demande</h2>
  {% if demande_admission %}
  <p>Nom: {{ demande_admission.Information_Personnel.nom }}</p>
  <p>Prénom: {{ demande_admission.Information_Personnel.prenom }}</p>
  <p>Envoyé le : {{ demande_admission.date_Soumision }}</p>
  <p>
    Statut de la demande: {{ demande_admission.get_statut_demande_display }}
  </p>
  <p>
    Type de la demande : {{ demande_admission.ProgrammeTrimestre.programme.type_admission }}
  </p>
  <p>Programme et Trimestre : {{ demande_admission.ProgrammeTrimestre }}</p>

  {% if demande_admission.statut_demande == 'attente' %}
  <p>
    Votre demande est en attente de traitement. Nous vous informerons dès qu'il
    y aura des mises à jour.
  </p>
  <p>
    Merci de choisir l'UQAM pour poursuivre vos études supérieures. Nous sommes
    impatients de vous accueillir sur notre campus.
  </p>
  {% elif demande_admission.statut_demande == 'accepte' %}
  <p>
    Félicitations ! Votre demande a été acceptée. Vous recevrez bientôt des
    instructions pour la suite du processus.
  </p>
  {% elif demande_admission.statut_demande == 'refus' %}
  <p>
    Malheureusement, votre demande a été refusée. Si vous avez des questions,
    veuillez nous contacter.
  </p>
  {% endif %} {% else %}
  <p>Aucune demande trouvée.</p>
  {% endif %}
</div>
{% endblock %} {% block extra_css %}
<link rel="stylesheet" href="{% static 'css/etat_demande.css' %}" />
<style>
  body {
    font-family: Arial, sans-serif;
    background-color: #f2f2f2;
    margin: 0;
    padding: 0;
  }

  div {
    max-width: 600px;
    margin: 50px auto;
    background-color: #fff;
    padding: 20px;
    border-radius: 8px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
  }

  h2 {
    color: #333;
  }

  p {
    color: #555;
    margin-bottom: 15px;
  }
  .demande-container {
    text-align: center;
    color: dodgerblue;
  }

  .demande-container p {
    margin: 10px 0;
  }

  .demande-container h2 {
    margin-bottom: 20px;
    font-size: 1.5em;
  }

  /* Add any additional styling as needed */
</style>
{% endblock %}

prj_Admission_DT/Projet_admission/Utilisateurs/templates/Utilisateurs/login.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="login_form">
        <form method="post">
          {% csrf_token %}
          <h2>Connexion</h2>
          <div class="form-_group">
            <label for="username">Nom d'utilisateur</label>
            <input type="text" name="code_user" required class="form_control" />
          </div>
          <div class="form_group">
            <label for="password">Mot de passe</label>
            <input
              type="password"
              id="password"
              name="password"
              required
              class="form_control"
            />
          </div>
          <button type="submit" class="btn btn-primary">Se connecter</button>
        </form>
        <p id="Error" class="Error">{{ error_message }}</p>
        <p class="register_link">
          Vous n'avez pas de compte ?
          <a href="{% url 'register_user' %}">S'inscrire ici</a><br />
          ou
          <a href="{% url 'register_user' %}">Mot de passe oublié ?</a>
        </p>
      </div>
    </div>
    <div class="col-md-6">
      <div class="image_container">
        <img
          src="/static/img/logo_registre.avif"
          alt="Student Image"
          class="student_image img_fluid"
        />
      </div>
    </div>
  </div>
</div>
{% endblock %} {% block extra_css %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/login_user.css' %}"
/>
{% endblock %}

prj_Admission_DT/Projet_admission/Utilisateurs/templates/Utilisateurs/registre.html
{% extends 'base.html' %} {% block content %} {% load static %}
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="registration-form">
        <form method="post" onsubmit="return test()">
          {% csrf_token %}
          <h2>Création d'un compte utilisateur</h2>
          <p id="Error" class="Error"></p>
          <p class="Error">{{message}}</p>
          <div class="form-group">
            <label for="code_user">Code Utilisateur</label>
            <input type="text" id="code_user" name="code_user" required />
          </div>
          <div class="form-group">
            <label for="password">Mot de passe</label>
            <input type="password" id="password" name="password" required />
          </div>
          <div class="form-group">
            <label for="password">Confirmation Mot de passe</label>
            <input
              type="password"
              id="passwordConfrimer"
              name="confirmation_password"
              required
            />
          </div>
          <div class="form-group">
            <label for="email">Courriel</label>
            <input type="email" id="email" name="email" required />
          </div>
          <button type="submit" class="btn btn-primary">S'inscrire</button>
          <p style="color: red; text-align: center">{{ error_message }}</p>
        </form>
        <p class="register_link">
          Vous n'avez un de compte ?
          <a href="{% url 'admission' %}">Se connect </a>
        </p>
      </div>
    </div>
    <div class="col-md-6">
      <div class="image-container">
        <img
          src="/static/img/registre.jpg"
          alt="Student Image"
          class="student_image"
        />
      </div>
    </div>
  </div>
</div>
{% endblock %} {% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/registre.css' %}" />
{% endblock %} {% block extra_js %}
<script type="text/javascript" src="{% static 'js/registre.js' %}"></script>
{% endblock %}